### ISSUE TITLE
Marker fill style

### ISSUE THREAD

**Issue by nkoep** [nschloe/matplotlib2tikz#101]
Hey,

I noticed that a marker fillstyle of `none` in matplotlib always translates to the mark option `fill=black` in pgfplots. This seems to be as easy as attaching `fill opacity=0` to the [mark_options](https://github.com/nschloe/matplotlib2tikz/blob/8ed5af67fdf7fd8113dea6fecff5b2cf1b541794/matplotlib2tikz/line2d.py#L53) inside the `draw_line2d` function.

Regards

**Comment by nschloe** [comment]
Can you give me a small python example that generates a plot thats translated incorrectly?

**Comment by nkoep** [comment]
Sorry for getting back to just now. Here's a quick example:

```python
import os

import numpy as np
import matplotlib.pyplot as plt

from matplotlib2tikz import save


def main():
    N = 100
    t = np.linspace(0, 1, N)
    x = np.arange(N)

    plt.plot(t, x, "-o", fillstyle="none")

    plt.tight_layout()
    plt.show()
    save("ex.tikz", figureheight=r"\figureheight", figurewidth=r"\figurewidth")


if __name__ == "__main__":
    main()
```
and here's the latex glue code:
```latex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepackage{tikzscale}

\newlength\figureheight
\newlength\figurewidth
\setlength\figureheight{7.5cm}
\setlength\figurewidth{15cm}

\begin{document}

\begin{figure}[!h]
  \centering
  \includegraphics[width=\textwidth]{ex.tikz}
\end{figure}

\end{document}
```

**Comment by nschloe** [comment]
Fixed. New version to be released later today.
