### ISSUE TITLE
`! Extra }, or forgotten \endgroup` at `\end{tikzpicture}`

### ISSUE THREAD

**Issue by antonioadaldo** [nschloe/matplotlib2tikz#107]
I get an `! Extra }` error at the last line of the self-generated picture. I am using pdflatex and `\pgfplotsset{compat=newest}`.

**Comment by daniel-edler** [comment]
Can you give us a minimal working example (mwe)? (Or in that case mnwe ;-) )

**Comment by nschloe** [comment]
Closing for lack of response; feel free to reopen with an MWE.
