### ISSUE TITLE
Grid on top of plot

### ISSUE THREAD

**Issue by m-rossi** [nschloe/matplotlib2tikz#109]
If I activate the grid in matplotlib in an axes, it is drawn on top of e.g. lineplots because of the axis option `axis on top`.

The example code
```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib2tikz

x = np.linspace(-1, 1)

plt.plot(x, x**2, linewidth=5)
plt.grid('on')

matplotlib2tikz.save('test.tex')
```
results in the following image:
![test](https://cloud.githubusercontent.com/assets/4509134/18230801/b0c493e6-72a6-11e6-92f3-eebec2d7300d.png)

The axis option `axis on top` is caused by https://github.com/nschloe/matplotlib2tikz/blob/master/matplotlib2tikz/axes.py#L84. Maybe just the axis and ticks should be on top of lineplots etc.? However I'm not sure how to do this in pgfplots.

**Comment by nschloe** [comment]
I'm not sure if I understand. What's the issue here? mpl2tikz tries to represent the mpl image as good as possible, so if the grid is above the plot there, it's carried over the pgfplots. If you don't want that, set `set_axisbelow(False)` on the axis in mpl.

**Comment by m-rossi** [comment]
Oh, you are right, I just realised matplotlib also draws the grid on top of the lineplot as default. It is not that obvious, because they are just small dots. I will use `set_axisbelow(False)` in the future. Thanks!
