### ISSUE TITLE
Minor ticks are ignored

### ISSUE THREAD

**Issue by oschoudhury** [nschloe/matplotlib2tikz#122]
If I run matplotlib and set the minor ticks on, `matplotlib2tikz` will not save those minor ticks. I put them explicitly on in my matplotlibrc-file (options are available since version 1.5), so I would love to see it every time, but here is a minimum working example:

    import matplotlib.pyplot as plt 
    from matplotlib2tikz import save as tikz_save

    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.plot([1.1, 2.1, 3.1], [4.1, 5.1, 6.1])
    ax.minorticks_on()
    tikz_save('test.tikz', strict=True)

This produce the following output in test.tikz:

    % This file was created by matplotlib2tikz v0.5.15.
    \begin{tikzpicture}
    
    \definecolor{color0}{rgb}{0.12156862745098,0.466666666666667,0.705882352941177}
    
    \begin{axis}[
    xmin=1, xmax=3.2,
    ymin=4, ymax=6.2,
    xtick={1,1.25,1.5,1.75,2,2.25,2.5,2.75,3,3.25},
    ytick={4,4.25,4.5,4.75,5,5.25,5.5,5.75,6,6.25},
    x grid style={lightgray!92.026143790849673!black},
    y grid style={lightgray!92.026143790849673!black}
    ]
    \addplot [line width=1.0pt, color0]
    table {%
    1.1 4.1
    2.1 5.1
    3.1 6.1
    };
    \end{axis}
    
    \end{tikzpicture}%

I do see the explicit command for putting the major ticks, as I did put `strict=True`. It should be relatively easy to add support for minor ticks imho.

There are two side notes that I want to make too, as things that I noticed. They don't bother me, so I did not put them as separate issues but I can submit two new issues if you want to. First side note, I put custom widths and sizes for the ticks in my matplotlibrc-file which aren't reproduced. Second side note, I noticed that it puts `4` as the first y-tick in the tikz picture, but matplotlib version 2.0b4 will put `4.00` in my plot and matplotlib version 1.4.2 will put `4.0`. Not sure if it is one of my own settings that influences this, or if it is purely matplotlib.

**Comment by nschloe** [comment]
> It should be relatively easy to add support for minor ticks imho.

Happy about a PR then! :smiley:

**Comment by nschloe** [comment]
> They don't bother me, so I did not put them as separate issues.

Chances are those will be forgotten. If you find out more about it, or if stresses out too much, I'd say open a new issue.

**Comment by oschoudhury** [comment]
I'll have a look at the code in a few days and see if I can submit a PR.

**Comment by nschloe** [comment]
Around [here](https://github.com/nschloe/matplotlib2tikz/blob/master/matplotlib2tikz/axes.py#L152) would probably be a good place to look.

**Comment by nschloe** [comment]
Fixed by PR #123.
