### ISSUE TITLE
Missing \end{groupplot} for subplot

### ISSUE THREAD

**Issue by noirchen** [nschloe/matplotlib2tikz#124]
I use matplotlib2tikz to generate a tikz file for a figure with several subplots, and I notice that when the number of subplots is smaller than row*col, the final tikz file won't compile because of missing `\end{groupplot}`. A minimal working python template looks like this.
```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, np.pi)

fig = plt.figure()
fignum = 8  # the problem goes away if fignum is 9
for subid in range(fignum):
    sub = fig.add_subplot(3, 3, subid + 1)
    y = np.sin(x)
    sub.plot(x, y)

from matplotlib2tikz import save as tikz_save
tikz_save('test.tikz')
```
But if `fignum` is 9 in the code above, the resulting tikz is compilable. I can work around this by either manually adding `\end{groupplot}` to the tikz file, or changing the row and column number. I think a quick patch will work.

**Comment by nschloe** [comment]
Fix released, thanks for the report.
