### ISSUE TITLE
pip installation fails: ImportError: No module named PIL

### ISSUE THREAD

**Issue by kidmose** [nschloe/matplotlib2tikz#127]
trying to install with `pip` in a virtual env on linux mint 18 fails:

    (env27) USERNAME@BOX ~PATH $ python --version
    Python 2.7.12
    (env27) USERNAME@BOX ~PATH $ pip --version
    pip 8.1.2 from /home/USERNAMEPATH/env27/local/lib/python2.7/site-packages (python 2.7)
    (env27) USERNAME@BOX ~PATH $ pip install matplotlib2tikz
    Collecting matplotlib2tikz
      Using cached matplotlib2tikz-0.5.16.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-MfzOn6/matplotlib2tikz/setup.py", line 7, in <module>
            from matplotlib2tikz import __version__, __license__, __author__, __email__
          File "matplotlib2tikz/__init__.py", line 15, in <module>
            from matplotlib2tikz.save import save
          File "matplotlib2tikz/save.py", line 6, in <module>
            from . import image as img
          File "matplotlib2tikz/image.py", line 6, in <module>
            import PIL
        ImportError: No module named PIL
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MfzOn6/matplotlib2tikz/
    You are using pip version 8.1.2, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    (env27) USERNAME@BOX ~PATH $ 

*EDIT:* upgrading to pip to 9.0.1 doesn't help

Suggestions as to why?

**Comment by nschloe** [comment]
No idea. `requirements.txt` lists `Pillow` so pip should pick up on this. Have you tried installing Pillow separately?

**Comment by kidmose** [comment]
Manually installing pillow solved my problem, thanks;

    (env27) USERNAME@BOX ~PATH $ pip install pillow
    Collecting pillow
      Downloading Pillow-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
        100% |████████████████████████████████| 5.6MB 165kB/s 
    Collecting olefile (from pillow)
      Downloading olefile-0.44.zip (74kB)
        100% |████████████████████████████████| 81kB 785kB/s 
    Building wheels for collected packages: olefile
      Running setup.py bdist_wheel for olefile ... done
      Stored in directory: /home/USERNAME/.cache/pip/wheels/20/58/49/cc7bd00345397059149a10b0259ef38b867935ea2ecff99a9b
    Successfully built olefile
    Installing collected packages: olefile, pillow
    Successfully installed olefile-0.44 pillow-4.0.0
    (env27) USERNAME@BOX ~PATH $ pip install matplotlib2tikz
    Collecting matplotlib2tikz
      Using cached matplotlib2tikz-0.5.16.tar.gz
    Building wheels for collected packages: matplotlib2tikz
      Running setup.py bdist_wheel for matplotlib2tikz ... done
      Stored in directory: /home/USERNAME/.cache/pip/wheels/41/4f/87/63fc4df5294c688f447f92255e40842917b217eb84ef93ee3b
    Successfully built matplotlib2tikz
    Installing collected packages: matplotlib2tikz
    Successfully installed matplotlib2tikz-0.5.16
    (env27) USERNAME@BOX ~PATH $
