### ISSUE TITLE
tex_relative_path_to_data ignored while saving

### ISSUE THREAD

**Issue by boeddeker** [nschloe/matplotlib2tikz#129]
When the `tex_relative_path_to_data` is set to some folder, this is correct set in the tex file, but the image is stored at the side of the tex file.

Is this the intended behavior?

If no, I could make a PR.

`tikz_save('something.tex', tex_relative_path_to_data='./out/')`

```
$ ls
./something.tex
./img1.png
$ cat ./something.tex
...
\addplot graphics [includegraphics cmd=\pgfimage,xmin=-0.5, xmax=399.5, ymin=-0.5, ymax=512.5] {./out/img1.png};
...
```

**Comment by nschloe** [comment]
That looks like a bug. A PR would be great!

**Comment by boeddeker** [comment]
Ok, then I will prepare a PR.

**Comment by boeddeker** [comment]
I think my assumption was wrong.
tex_relative_path_to_data is not for storing the image relative to the tikz file, the parameter describes the relative path to root tex file.
