### ISSUE TITLE
Can't load matplotlib2tikz with deficient web connection

### ISSUE THREAD

**Issue by tgrandje** [nschloe/matplotlib2tikz#141]
Hello

The use of pipdated can cause a failure of matplotlib2tikz when having a deficient web connexion (for exemple : at work, our network+proxy won't allow pip methods).

I had to edit the \_\_init__.py file of matplotlib2tikz to let a "pipdated failure" happen whithout crashing matplotlib2tikz :

replaced :
```
import pipdated
if pipdated.needs_checking('matplotlib2tikz'):
    msg = pipdated.check('matplotlib2tikz', __version__)
    if msg:
        print(msg)
```

by :
```
import pipdated
try:
    if pipdated.needs_checking('matplotlib2tikz'):
        msg = pipdated.check('matplotlib2tikz', __version__)
        if msg:
            print(msg)
except:
    print "pipdated error"
    pass
```

Regards
tgrandje

**Comment by nschloe** [comment]
Thanks for the report. This was a pipdated issue, fixed now.
