### ISSUE TITLE
flipped picture in plot in Latex

### ISSUE THREAD

**Issue by danielhkl** [nschloe/matplotlib2tikz#145]
I create a spectrogram plot as follows:
```python
image = ax.imshow(
    signal,
    interpolation='nearest',
    vmin=limits[0],
    vmax=limits[1],
    cmap=cmap,
    origin="lower",
    norm=norm,
)
```
A .png file is created, but after saving it with matplotlib2tikz.save, it is flipped. So up and down is transposed. From my point of view it is a bug in matplotlib. It has something to do with the origin parameter: image.py:
```python
mpl.pyplot.imsave(fname=filename,
                      arr=img_array,                                
                      cmap=obj.get_cmap(),
                      vmin=clims[0],
                      vmax=clims[1],
                      origin=obj.origin
                      )
```
This bug can be bypassed with `numpy.flipud(img_array)` in matplotlib2tikz.

**Comment by nschloe** [comment]
Closing per https://github.com/nschloe/matplotlib2tikz/pull/147.

**Comment by boeddeker** [comment]
It looks that this is a bug in matplotlib, because in the past `origin=obj.origin` has done the correct things.
Maybe it is now better to remove the `origin` arg in imsave.

**Comment by nschloe** [comment]
Alright, we clearly need a unit test for this. Anyone?

**Comment by danielhkl** [comment]
Perhaps, the easiest way to test such an issue is to create an example (Jupyter) notebook. So everyone can see wether imsave works correctly or not. I suggest to create an example folder for this kind of example notebooks. What do you think?

**Comment by nschloe** [comment]
A better place for this is probably the tests. Those get executed automatically, so once we have a test for this one in, we can be sure that we don't accidentally mess it up again in the future.

**Comment by nschloe** [comment]
I've played around with multiple images, upside down too, and found no issue. Perhaps this has accidentally been resolved by now? If something is still wrong, we need an MWE. Closing for now.
