### ISSUE TITLE
Plotmark 'o' not readily accesible

### ISSUE THREAD

**Issue by hariskurtovic** [nschloe/matplotlib2tikz#153]
```python
plot(1,1,'o',markerfacecolor=None)
```
Always returns `*` as marker. I tried transparencies, facecolors but nothing helped. I looked it up in the source and it seems that it does not properly read the facecolor. Didn't debug it though. 

The problem is surely with `(marker_face_color is not None)`.

This is around line 270 in line2d.py
```python
    try:
        pgfplots_marker = _MP_MARKER2PGF_MARKER[mpl_marker]
        if (marker_face_color is not None) and pgfplots_marker == 'o':
            pgfplots_marker = 'o' # I changed this line so that I can get the needed result
            data['pgfplots libs'].add('plotmarks')
        marker_options = None
        return (data, pgfplots_marker, marker_options)
    except KeyError:
        pass
```

**Comment by nschloe** [comment]
Do I understand correctly that you want empty circles as markers?

In this case,
```python
plot(1,1,'o',markerfacecolor=None)
```
is not correct; matplotlib produces full circles (tested with mpl 2.0.2). You need
```python
plot(1,1,'o',markerfacecolor='none')
```
