### ISSUE TITLE
add possibility to get the LaTeX output in a string

### ISSUE THREAD

**Issue by tgy** [nschloe/matplotlib2tikz#157]
I would like to get the output of `matplotlib2tikz.save` as a string rather than having to save it to a file directly. The main usage would be to use the LaTeX generated by `matplotlib2tikz` in a template.

This is fairly easy to implement. A new `to_latex` function can be rewritten exactly like the current `save` function except that instead of outputing to a file, a string is constructed and returned. Then the `save` method becomes a call to the `to_latex` function followed by a file write.

I can submit a PR.

**Comment by nschloe** [comment]
Excellent suggestion. I have no idea why this hasn't come up earlier.

Just took a few minutes to fix this. There now is `get_tikz_code()` with the same signature as `save()`. It returns a multiline string.

**Comment by tgy** [comment]
That was super fast. Thanks, you rock! :)

**Comment by lucaventurini** [comment]
This is great. Could you add it to the readme? I always forget how to do it :)

**Comment by nschloe** [comment]
@lucaventurini Did that just now in a local branch, will be part of the next release.
