### ISSUE TITLE
0.6.5 sources missing on pypi

### ISSUE THREAD

**Issue by marbre** [nschloe/matplotlib2tikz#159]
Seems the tarball was not uploaded to pypi.

**Comment by nschloe** [comment]
Is it needed though?

**Comment by marbre** [comment]
In gentoo we normally fetch sources from pypi and I actually moved the packed from the science overlay to the main tree. Thus it is no hard requirement, but it would be nice :)

**Comment by nschloe** [comment]
Can you take the gz from GitHub, https://github.com/nschloe/matplotlib2tikz/releases?

**Comment by marbre** [comment]
Okay, I'll switch over and hope the PR gets accepted.

**Comment by nschloe** [comment]
Let me know if you need any further help. (I've used Gentoo years ago so I'm still a bit attached to it.)
