### ISSUE TITLE
when legend doesn't contain all lines, color is out of wack

### ISSUE THREAD

**Issue by spott** [nschloe/matplotlib2tikz#167]
For lines that aren't included in the legend, `forget plot` needs to be added to the `addplot` options.

pseudocode:
```python
plt.plot(x,y1, label=y1)
plt.plot(x,y2, label=None)
plt.plot(x,y3, label=None)
plt.plot(x,y4, label=y4)
plt.legend()
tikz_save(...)
```
will produce a legend where `y4` is colored like `y2`.

I'll come back and attach a minimal working example when I have time.

**Comment by nschloe** [comment]
Fixed now.
