### ISSUE TITLE
Tick length/width, Axis edge width & ticks covered by image

### ISSUE THREAD

**Issue by vineetsoni** [nschloe/matplotlib2tikz#184]
Hi,

I'm new to python-matplotlib and as such new to matplotlib2tikz. So, pardon me if the script looks ugly or I am doing something wrong!!

Below is a small sample script I made to highlight some issues that I am facing.

```python
import matplotlib.pyplot as plt
import numpy as np

N = np.zeros((512,512))

plt.rcParams['axes.edgecolor'] = 'k'
plt.rcParams['axes.linewidth'] = 1
plt.rcParams['axes.grid'] = 'False'
plt.rcParams['xtick.major.size'] = 4.5
plt.rcParams['xtick.minor.size'] = 2.5
plt.rcParams['xtick.major.width'] = 1
plt.rcParams['xtick.minor.width'] = 0.5
plt.rcParams['xtick.minor.visible'] = 'True'
plt.rcParams['ytick.major.size'] = 4.5
plt.rcParams['ytick.minor.size'] = 2.5
plt.rcParams['ytick.major.width'] = 1
plt.rcParams['ytick.minor.width'] = 0.5
plt.rcParams['ytick.minor.visible'] = 'True'

plt.imshow(N, cmap='gray', clim=(-1,0))
plt.colorbar()
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.tick_params(axis='both', which='both', direction='in', left='on', right='on', bottom='on', top='on')

from matplotlib2tikz import save as tikz_save
tikz_save('image.tex')
```

So here are the issues:

1. Axis edge width does not show any effect when exported using matplotlib2tikz.
2. The same is true for the width and length of major-minor ticks.
3. The ticks are covered by the (white) image, hence not visible in the Latex output. However, if one adds `axis on top,` in the matplotlib2tikz generated TEX file, it works fine.
4. The tick color always gets set to grey when exported by matplotlib2tikz. The only way that I have came across to change it is to add `x tick style={color=black}` in the TEX file.

**All these issues are non-existent if one exports the figure in a PDF file.**

Let me know, if you need some more inputs from my side.

Cheers

**Comment by nschloe** [comment]
Thanks for the report!

You're right, none of these things work very well at the moment. The general philosophy of matplotlib2tikz is to convert matplotlib defaults to pgfplots defaults, even if they differ (for example in the tick colors). Using the `strict` option might get you somewhere – it tries to be more faithful to the matplotlib original. As far as I remember, nobody has paid much attention to the ticks, so perhaps this still needs fixing in the code.

You could make development easier if you open a new issue for each little thing you find is wrong, along with a minimal Python script that produces a figure with the missing feature. This way, we immediately have a test for it.

**Comment by vineetsoni** [comment]
Thanks for the reply!

As you suggested, I have opened new issue for each of the points with the python scripts focusing on individual problem.

**Comment by nschloe** [comment]
Perfect! Let's close this one here; I'll have the other bugs to look at in the future.
