### ISSUE TITLE
Ticks covered by the image

### ISSUE THREAD

**Issue by vineetsoni** [nschloe/matplotlib2tikz#188]
The image plots seem to cover the ticks.
However, the same doesn't do so if one exports in PDF format.

Please have a look at the script below that would help you reproduce the issue:
```python
import matplotlib.pyplot as plt
import numpy as np

N = np.zeros((512,512))

plt.imshow(N, cmap='gray', clim=(-1,0))
plt.tick_params(direction='in')

from matplotlib2tikz import save as tikz_save
tikz_save('tickcover.tex')
```

The output should look like:
![tickcover](https://user-images.githubusercontent.com/23280649/27516440-0b14b48e-59ba-11e7-9eae-4ea9a5211ddf.png)

However, with matplotlib2tikz, it looks like:
![tickcoverplot](https://user-images.githubusercontent.com/23280649/27516441-12c2fbe6-59ba-11e7-8042-7167cd548843.png)

I think the solution to this issue is to add `axis on top` in the `axis[]` of matplotlib2tikz generated TEX file.

**Comment by nschloe** [comment]
I'm afraid is won't fix. The reason is that, in matplotlib, you have three possible values for `get_axisbelow()`:

        * `True` (zorder = 0.5):   Ticks and gridlines are below all Artists.
        * `'line'` (zorder = 1.5): Ticks and gridlines are above patches (e.g. rectangles, images) but still below lines / markers.
        * `False` (zorder = 2.5):  Ticks and gridlines are above patches and lines/markers.

Pgfplots only has the `axis on top` keyword. In your plot, you have the value ``line`, so it's that inbetwee value that has no match in Pgfplots.
