### ISSUE TITLE
Manual legend

### ISSUE THREAD

**Issue by haji-ali** [nschloe/matplotlib2tikz#189]
Hello,

I implemented a modification of the rendering of legends that I hope you will find interesting.
See the diff [here](https://github.com/nschloe/matplotlib2tikz/compare/master...haji-ali:manual-legend)

When passing `manual_legend=True`, the legend is rendered using `\matrix` instead of `legend`. This is much more flexible and allows for easy customization of the legend (for example changing the order to match the order from `matplotlib`).

Also in this commit is what I believe is a fix to color.py that returns `none` when the alpha value is exactly zero.

**Comment by nschloe** [comment]
Thanks for the hint! It sounds like the color fix definitely warrants a PR. Would you create one with just that change?

The legend suggestion sound more like a custom solution; not sure how interesting it would be for others. Related to that, does the order of the legends wrong? If yes, it should definitely be treated as a bug.

**Comment by haji-ali** [comment]
The ordering in tikz legend depends on the ordering of the plots, which also determines the z-order.
Right now, matplotlib2tikz uses the z-order of matplotlib to determine the ordering of the plots which automatically sets the ordering in the legend. The only way I know to specify these two orderings separately is to create a custom legend using `\matrix`.

I will create a PR with the color.py change. Also, I forgot to mention that I also had to change the fix in path.py to remove line 17 which checks that the vertices are equal. This is to remove the empty paths that matplotlib creates, however in some of my plots the vertices were different in those paths.

**Comment by nschloe** [comment]
> Also, I forgot to mention that I also had to change the fix in path.py to remove line 17 which checks that the vertices are equal. This is to remove the empty paths that matplotlib creates, however in some of my plots the vertices were different in those paths.

The remaining check would be
```
    if len(path.vertices) == 2 and 'fill opacity=0' in draw_options:
        return data, '
```
which is too strict: Mark-only paths with two vertices get kicked out.

**Comment by lordievader** [comment]
> Related to that, does the order of the legends wrong? If yes, it should definitely be treated as a bug.
I would say yes. For a bar plot I have with a line in the middle the legend labels are reordered in tikz. 
In Matplotlib the two bar plots are created first and then the line plot. The legend in tikz shows the label from the line plot first and then the two bar plots.

If you would like someone to test the `\matrix` patch, I'd be happy to help.

**Comment by nschloe** [comment]
Perhaps best open up a separate bug (with an MWE) for the legend ordering bug.

**Comment by nschloe** [comment]
Some significant legend improvements have landed in matplotlib2tikz now which will hopefully cover a lot of use cases mentioned here. Replacing the legend by `\matrix` seems a bit too intrusive.

What we could perhaps do to allow for more customization in mpl2tikz is to generate an object that makes is easy to manipulate and which generates the plot afterwards. I'll think about that.
