### ISSUE TITLE
Segmentation of long data series to smaller, forgotten chunks so as not to exceed pool memory sizes

### ISSUE THREAD

**Issue by twomers** [nschloe/matplotlib2tikz#19]
I have an issue that when I generate tikz files from long data segments, tex complains that it runs short in pool memory. I have found a fix for this which plots the long data segments without limiting the resolution of the data. 

If I was plotting some data with, say,10,000 data points, and it breaks the pool size limits with the following:
```latex
\addplot [color=black,solid,line width=0.25]
coordinates{ 1...10000 }
```
I simply break it up to a few smaller chunks and add the "forget plot" parameter to the \addplot command like so: 
```latex
\addplot [color=black,solid,line width=0.25,forget plot]
coordinates{ 0...2499 }
\addplot [color=black,solid,line width=0.25,forget plot]
coordinates{ 2500...4999}
\addplot [color=black,solid,line width=0.25,forget plot]
coordinates{ 5000..7499. }
\addplot [color=black,solid,line width=0.25]
coordinates{ 7500...9999}
```
making sure to not `forget plot` one of them so that the data series can still be added to a legend, if desired. This works fine. It would be great if this could be automatically introduced to your package. Perhaps leaving it as a parameter like so would be an appropriate interface, like so:
```python
tikz_save( fName, maxSeriesLength=2500 )
```
probably with a pessimistic default parameter (better safe than sorry!). I'm not sure how many data points are realistic to ensure tex won't throw an error, but it shouldn't be hard to find this out. Leaving it as a parameter can allow arbitrary lengths for users with specific memory requirements. 

I hope this can be incorporated easily!

Niall

**Comment by nschloe** [comment]
Sounds like a classical TeX memory issue. Typically, these things don't happen anymore with lualatex, so I'm always recommending the latter. (Also I think it's the default LaTeX compiler on most platforms now.)

Feel free to reopen if you continue to hit the issue with lualatex.
