### ISSUE TITLE
Legend ordering bug

### ISSUE THREAD

**Issue by haji-ali** [nschloe/matplotlib2tikz#192]
Below is an a MWE illustrating the issue discussed in #189 

```python
from matplotlib2tikz import save as tikz_save
import matplotlib.pyplot as plt
x = np.linspace(0, 1,5)
l1, = plt.plot(x, x, '', zorder=1)
l2, = plt.plot(x, x**2, '', zorder=2)
plt.legend((l2, l1), ("x^2", "x"))

tikz_save('out.tex', plt.gcf())
# tikz_save('out_man.tex', plt.gcf(), manual_legend=True) # This is using the manual-legend fix
```

The lines are wrongly labeled in out.tex. This can be fixed by changing the zorder property, but then the order the lines appear will be reversed.

The manual-legend fix can be found [here](https://github.com/nschloe/matplotlib2tikz/compare/master...haji-ali:manual-legend)

**Comment by nschloe** [comment]
PR #278 brought some legend fixes; this bug is now fixed, too.

![f](https://user-images.githubusercontent.com/181628/54678492-859ba300-4b05-11e9-80e1-fbfd7841fdd1.png)
