### ISSUE TITLE
Wrong legend with markers (bad \addlegendimage command)

### ISSUE THREAD

**Issue by Globulle** [nschloe/matplotlib2tikz#202]
I noticed markers (alone or associated to line) display is blocked in the legend because of wrong (and useless in my case) `\addlegendimage` commands in the TikZ code (matplotlib2tikz v0.6.13). Here is a minimal example :

### Python code and legend result
```python
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.1)
s = np.sin(2*np.pi*t)
s2 = np.cos(2*np.pi*t)
plt.plot(t, s, '+', label='crosses')
plt.plot(t, s2, '-o', label='line/dots')
plt.legend()

from matplotlib2tikz import save as tikz_save
tikz_save('test.tex')
```
![bug_marker_python](https://user-images.githubusercontent.com/11587267/30025505-22f8cc1a-9179-11e7-8f2a-05322488a371.png)

### Generated TeX code and legend result
```latex
\begin{tikzpicture}

\begin{axis}[
xmin=0, xmax=2,
ymin=-1, ymax=1,
axis on top,
tick pos=both,
legend entries={{crosses},{line/dots}},
legend cell align={left}
]
\addlegendimage{no markers, blue}
\addlegendimage{no markers, green!50.0!black}
\addplot [blue, mark=+, mark size=3, mark options={solid}, only marks]
table {%
0 0
(...)
1.9 -0.587785252292473
};
\addplot [green!50.0!black, mark=*, mark size=3, mark options={solid,draw=black}]
table {%
0 1
(...)
1.9 0.809016994374947
};
\end{axis}

\end{tikzpicture}
```
![bug_marker_tex](https://user-images.githubusercontent.com/11587267/30025642-be9a1700-9179-11e7-8dd3-43218b35428f.png)

### Solution
Removing the lines 
```
\addlegendimage{no markers, blue}
\addlegendimage{no markers, green!50.0!black}
```
solves the issue : 
![bug_marker_tex_2](https://user-images.githubusercontent.com/11587267/30025905-f97c2754-917a-11e7-86b2-5c1bc623f094.png)

**Comment by mattia-** [comment]
I came here wanting to open this same issue exactly. It's not a big deal, a little bit of sed will do the trick even on a batch plot, but it's still annoying nonetheless

**Comment by homocomputeris** [comment]
I have the same issue
```LaTeX
% This file was created by matplotlib2tikz v0.6.15.
\begin{tikzpicture}

\definecolor{color0}{rgb}{0.12156862745098,0.466666666666667,0.705882352941177}
\definecolor{color1}{rgb}{1,0.498039215686275,0.0549019607843137}

\begin{axis}[
xlabel={$\log_{10} cost$},
ylabel={$\log_{10} error$},
xmin=2, xmax=5,
ymin=-12, ymax=0,
xtick={2,2.5,3,3.5,4,4.5,5},
xticklabels={$2.0$,$2.5$,$3.0$,$3.5$,$4.0$,$4.5$,$5.0$},
ytick={-12,-10,-8,-6,-4,-2,0},
yticklabels={$-12$,$-10$,$-8$,$-6$,$-4$,$-2$,$0$},
tick align=outside,
tick pos=left,
x grid style={white!69.01960784313725!black},
y grid style={white!69.01960784313725!black},
legend style={draw=white!80.0!black},
legend entries={{$\mathrm{RK}_{7}^{[6]}$},{$\mathrm{RKGL}_{3}^{[6]}$}},
legend cell align={left}
]
\addlegendimage{no markers, color0}
\addlegendimage{no markers, color1}
```

**Comment by jpnadas** [comment]
This issue is easily fixed by removing the code
```
     for handle in obj.legendHandles:
         try:
             # when using matplotlib colours like "darkred" or "darkorange",
             # `handle.get_color` will create nested RGBA codes
             # e.g. `[[ 0.54509804, 0., 0., 1.]]` which casuse mpl to throw an error.
             # catch this error, `numpy.squeeze` the colour code and try again
             try:
                 data, legend_color, _ = mycol.mpl_color2xcolor(
                     data, handle.get_color())
             except ValueError:
                 data, legend_color, _ = mycol.mpl_color2xcolor(
                     data, numpy.squeeze(handle.get_color()))
             data['legend colors'].append('\\addlegendimage{no markers, %s}\n'
                                         % legend_color)
         except AttributeError:
             pass
```

from legend.py

However, I don't know if removing this code will break something else.

**Comment by dajuno** [comment]
This is still an issue in the current version. @nschloe, is there any reason why this shouldn't be fixed as described by @jpnadas?

**Comment by nschloe** [comment]
> is there any reason

Well, I haven't tried the code, but I'm skeptical. Just look at the comment in the code that is to be removed.

That said, if you get the tests to run with the change, I'll be happy to merge the PR.

**Comment by jpnadas** [comment]
@nschole Removing the code is obviously a temporary solution, as the original problem which prompted the code to be added is still going to be there.

The best solution would be to identify all the line properties (marker type, line width, marker face color, marker size, etc) and include it in the legend.

That said, I am not sure why a separate legend image is being included, as simply adding the legend entry after the plot already gets all the line properties and creates the legend accordingly.

Do you have any idea why a second image entry is being added?

**Comment by nschloe** [comment]
> Do you have any idea why a second legend image entry is being added?

**Comment by DaneG123** [comment]
In your **.tex** script containing your matplotlib2tikz tikz code, simply comment out:

\addlegendimage{no markers, color}

like so:

%\addlegendimage{no markers, red}
%\addlegendimage{no markers, blue}

This fixed it for me. It isn't a permanent fix, but it only takes a few seconds for each image.

**Comment by Aikhjarto** [comment]
Whats the reason to use `\addlegendimage` in combination with `legend entries=`at all? IMHO `\addlegendentry` directly after `\addplot` would be more concise and less prone for errors (e.g.  no need to set marker styles at two position in the tikz code).
However, befor working on that, I would like to known if using `\addlegendentry` directly after `\addplot` might interfere with something that I'm not aware of.
