### ISSUE TITLE
No support for the contourf plots?

### ISSUE THREAD

**Issue by vineetsoni** [nschloe/matplotlib2tikz#208]
I tried very hard to make contourf plots work with this package. But, it seems that it is not supported at the moment? It is pity because this is such an excellent tool.

Can you please give me a hint how can I implement it? What document should I refer to do so? I have found out the pgfplot syntax for contourf plots, but I don't know where/how should I add it. 
I have already made tons of (line & image) plots. Now, if I can't make contourf plots with this tool, I would need to re-do all my plots to be consistent in the work.

Thanks!

**Comment by boeleman** [comment]
It is not optimal, but a workaround I've been using is to plot with contour and then manually combine the contour lines to make closed curves with cycle which can be filled with fill=color. I wish contourf was working properly too.

**Comment by nschloe** [comment]
contourf plots are supported and tested. If you find it not working, please reopen with _minimal_ Python example code that generates a non-working plot.
