### ISSUE TITLE
matplotlib2tikz: Dont know how to handle object <class 'matplotlib.offsetbox.AnnotationBbox'>.

### ISSUE THREAD

**Issue by berleon** [nschloe/matplotlib2tikz#213]
Hello,

It seems that matplotlib2tikz cannot handle `AnnotationBbox`. 
Would it be hard to add them? If you point me into the right direction, I might be able to add them.

Cheers, Leon

**Comment by nschloe** [comment]
I've recently added support for annotations, so I'll just go ahead and assume that this is fixed. :smile_cat: If not, feel free to reopen with an MWE.
