### ISSUE TITLE
Not correct histogram saving (log y axis)

### ISSUE THREAD

**Issue by agatatrovato** [nschloe/matplotlib2tikz#219]
I'm using python 2.7.14 and I'm using the save function of matplotlib2tikz to save a histogram but it looks like the edges of the histograms are not correctly saved. 
The are 2 problems:
- the coordinates of the edges are often repeated in couples while I expected one of the 2 should change to create the histogram shape
- the y coordinates are often zeros and, since the y axis is logarithmic, this creates weird effects when showing the plot inside the latex. I can replace by hand the zeros with small numbers but it's not a nice solution.
  
In the following the plot saved in pdf saved and the tex (renamed as .txt).
[Lambda.pdf](https://github.com/nschloe/matplotlib2tikz/files/1669962/Lambda.pdf)
[Lambda.txt](https://github.com/nschloe/matplotlib2tikz/files/1669963/Lambda.txt)

I attach also the plot I get when I use \input{Lambda.tex} inside my latex document, but to make my latex show it I had to modify the original Lambda.tex removing the calls to \mathdefault (that were not recognized) and I've replaced all the zeros in the y axis with 1e-5. Despite my modifications it does not look at all like the pdf saved in matplotlib.
<img width="563" alt="lambda_inside_latex" src="https://user-images.githubusercontent.com/35865211/35470920-527e6c24-0352-11e8-9f7c-9205c1bfb5cc.png">

Is it the log axis that creates these problems?
When I try to include the tex in my latex document I get also the error that \mathdefault is not known, is there some option to avoid using it?

Agata.

**Comment by nighthawk9** [comment]
I am having the same issues using Python 3.7.2. I am using a loglog plot and `\mathdefault{}` is also giving me errors as well as tikz/minor is not recognized.

**Comment by reinirf** [comment]
I also faced this issue and solved it by defining a do-nothing or pass-through command `\newcommand{\mathdefault}[1]{#1}` in my latex-file

**Comment by nschloe** [comment]
I need a Python MVCE so this I can try fixing it. Please comment or reopen with one.
