### ISSUE TITLE
Mistakes in legend for fillbetween

### ISSUE THREAD

**Issue by AxelS83** [nschloe/matplotlib2tikz#224]
Hi, 

I'm using the following code to plot my figure:
```python
import matplotlib as mpl
import matplotlib.pyplot as plt

import numpy as np
mpl.style.use('seaborn-colorblind')

from matplotlib2tikz import save as tikz_save


fig = plt.figure(figsize=(7,4))
ax = fig.add_subplot(111)
ax.fill_between([1, 2],[2, 2],[3, 3],color = 'red',alpha=0.2, label ='roh')
ax.fill_between([1, 2],[4, 4],[5, 5],color = 'blue',alpha=0.2, label ='kal')
ax.plot([1, 2],[2, 5],'k',label='ref')
ax.grid()
plt.legend()
tikz_save('minimalbeispiel.pgf', figureheight='4in', figurewidth='5in')
```
The python export of the figure looks fine:
![python_figure](https://user-images.githubusercontent.com/36321730/36058908-b13a162a-0e2c-11e8-8e56-36ac350ce58a.png)

But unfortunately the generated code in Tex looks like that:
![tex_view](https://user-images.githubusercontent.com/36321730/36058886-5b8330fe-0e2c-11e8-8db0-e6299588a6c2.png)

I don't know how to deal with it.
Best regards,
Axel

**Comment by pylipp** [comment]
I think #243 comes a little closer to what you want.
