### ISSUE TITLE
Annotate arrows with <|-|> not working properly

### ISSUE THREAD

**Issue by JacobEFO** [nschloe/matplotlib2tikz#235]
Hello you guys. I encountered an error with matplot2tikz.

The "Annotate" function with arrows with <|-|> option generates a simple line instead of the specified arrow.
The option <-> however works.

Currently I generate two plots, one with <|-|> and one with <-> with the following code: https://pastebin.com/xtanQFAG

Then I display it with the following LaTeX code using the PDFlatex builder: https://pastebin.com/Q6tBaKRt

The result is the following picture: https://imgur.com/a/QRxnXtC

I hope it is easy enough to replicate and understand.

Best regards Jacob

**Comment by pylipp** [comment]
The `<|-|>` arrow style is not supported by matplotlib2tikz (see https://github.com/nschloe/matplotlib2tikz/blob/master/matplotlib2tikz/text.py#L148). How would you create this arrow in Latex?

**Comment by pylipp** [comment]
You can see in `NotWorking.tex` that the arrow `\draw` command has no options. You can put `<|-|>` there, I just think it's not really visually pleasing.

**Comment by nschloe** [comment]
Fixed by #275.
