### ISSUE TITLE
Relative Path Produce undefined control sequneces under windows

### ISSUE THREAD

**Issue by glenflet** [nschloe/matplotlib2tikz#242]
https://github.com/nschloe/matplotlib2tikz/blob/73d5db7361f8dd6af787ba6801bf140c4524b766/matplotlib2tikz/files.py#L42

Using os.path.join, under windows use the path separator "\" when this appear in the latex output its treated as a control sequence, which normally produces the Tex error "! Undefined control sequence."

Under latex the path should always use "/" as the separator.

You can use `posixpath.join` under windows still, which should fix the problem.

**Comment by cassiersg** [comment]
@glenflet Can you check that #246 solves this issue ? I currently don't have a Windows machine for testing.
