### ISSUE TITLE
Empy contourf plot

### ISSUE THREAD

**Issue by srossi93** [nschloe/matplotlib2tikz#247]
Hi,

I'm having some issues with contourf plot that seems to produce empty plots. According to this PR [226](https://github.com/nschloe/matplotlib2tikz/pull/226), this should be supported by matplotlib2tikz. 

Minimal code:
```python
from scipy.stats import multivariate_normal
import numpy as np
import matplotlib.pylab as plt
import matplotlib2tikz     # matplotlib2tikz.__version__ = '0.6.13'

def plot_2d_gaussian(mean, cov,  nbins=200, zoom = 1 ):

    fig = plt.figure(figsize=[6, 6])
    ax = plt.gca()
    
    x_max = mean[0] + mean[0] / zoom
    x_min = mean[0] - mean[0] / zoom
    y_max = mean[1] + mean[1] / zoom
    y_min = mean[1] - mean[1] / zoom
    
    xi, yi = np.mgrid[x_min:x_max:nbins*1j, y_min:y_max:nbins*1j]
    pos = np.empty(xi.shape + (2,))
    pos[:, :, 0] = xi; 
    pos[:, :, 1] = yi
    zi = multivariate_normal(mean, cov, allow_singular=True, seed=0).pdf(pos)
    ax.contourf(xi, yi, zi, 250)

    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    return fig, ax

fig, ax = plot_2d_gaussian(np.array([1, 1]), np.eye(2), zoom=10)
fig.savefig('contourf.png')
matplotlib2tikz.save('./contourf.tex')
```
This is the result on a Jupiter notebook
![contourf](https://user-images.githubusercontent.com/11166137/44085354-87f15426-9fb9-11e8-83e2-427ac221a837.png)

And this after compiling the LaTeX 

![paper-figure1](https://user-images.githubusercontent.com/11166137/44085632-695375d4-9fba-11e8-99fa-bb06245e305f.png)

Indeed, the tex file is filled with just 
```tex
\addplot [only marks, fill=color181, colormap/viridis]
table{%
x                      y
+0.000000000000000e+00 +0.000000000000000e+00
};
```

As workaround, changing from `contourf` to `contour` works.

Matplotlib:
![contour](https://user-images.githubusercontent.com/11166137/44085786-d3a4f868-9fba-11e8-90e4-41650bd8821e.png)

LaTeX:
![paper-figure0](https://user-images.githubusercontent.com/11166137/44085778-cd6d63ea-9fba-11e8-8219-770420693783.png)

**Comment by nschloe** [comment]
Tested just now, it's working. Not sure how it was fixed though.

**Comment by srossi93** [comment]
Nice, thank you for the update.
