### ISSUE TITLE
Legend along with Extra Axis Parameters

### ISSUE THREAD

**Issue by hbanzhaf** [nschloe/matplotlib2tikz#250]
I would like to make a plot containing a legend. In addition to that, a string is passed to the _extra_axis_parameters_, which modifies the font size in the tikz picture. A minimal working example is provided below:
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib2tikz import save as tikz_save

x = np.linspace(1, 10)
y = np.linspace(1, 10)

plt.plot(x, y, label='f(x)')
plt.legend()

tikz_save('test.tikz', extra_axis_parameters=['font=\small'])
plt.show()
```

Without the line `plt.legend()` everything works as expected. However, inserting that line leads to the following error:
```
data["extra axis options"].add(cont)
AttributeError: 'list' object has no attribute 'add'
```
Any suggestions?

**Comment by ngc92** [comment]
I think `extra_axis_parameters` is supposed to be a dict. So 
```
tikz_save('test.tikz', extra_axis_parameters={'font' :'\small'})
```

**Comment by hbanzhaf** [comment]
You are right, passing one (or multiple parameters) as a set works. Using a dict did not work on my side.

**Comment by nschloe** [comment]
You can also specify lists now.
