### ISSUE TITLE
Invalid plots for out of range data

### ISSUE THREAD

**Issue by ngc92** [nschloe/matplotlib2tikz#251]
matplotlib2tikz generates invalid plots for functions with poles. In general, if any data is far outside the plotted axis (in particular, invisible in the plot), pgfplots may stop working with an error like
```
! Dimension too large.
<recently read> \pgfmath@x 
           
l.19 \end{axis}
```

A minimal example to reproduce this is 
```
import matplotlib.pyplot as plt
import matplotlib2tikz as m2t
plt.plot([0.0, 1.0], [0.0, 100000.0])
plt.ylim(0, 1)
m2t.save("test.pgf")
```

**Comment by nschloe** [comment]
There are several ways of handling this, all of them involving tinkering with the data. I don't like this being done automatically. I'd say the best way to deal with these problems is to manually edit the output tex file. Perhaps mpl2tikz can issue a warning or so that this may be necessary.
