### ISSUE TITLE
Control over number precision

### ISSUE THREAD

**Issue by PetePupalaikis** [nschloe/matplotlib2tikz#252]
Hi and thanks for this tool.  It is integrated in another tool that I'm making and is very useful.

My issue (actually a feature request) is control over the number precision.  I have downloaded the latest version 0.6.18.  For my purposes, I've globally replaced ever string that is:

    .15g

with:

    .6g

and like the results better - the amount of precision is great, the files are smaller, and is more easily digestible by LaTeX.  Obviously, a global change like that would upset others, but I'm recommending something simple like a number precision argument (defaults to 15) and would form the number inserted into the aforementioned strings.

I've seen other issues requested like this, but cannot seem to find that issue again right now.

If you like this idea, I would consider making the change myself and submitting it - otherwise, on my local machine I have this change.

By the way, the main impetus for this, which may seem silly, is that I'm developing a tool that works cross-platform and uses matplotlib2tikz.  Each platform comes up with slightly different numbers and it causes trouble for my unit-testing and version control if things keep changing.  I'm thinking with less that full precision, the resulting .tex files shouldn't be changing.

Thanks again

**Comment by PetePupalaikis** [comment]
I have a modification that adds this feature.  It adds an option argument called 'precision' to the tikz functions.  The value defaults to 15.  I call it with precision=6.  The precision is stored in the dictionary and used wherever necessary.  Therefore, the default behavior ought to be what it is now, but with my feature add.

I checked the change in on a local branch called 'precisionOption'.

I tried to run the PyTests - they all fail for some reason.  I did install the imageHash and PyTest.  I verified that it fails without my changes as well - so I don't know what I'm doing wrong.

I'm new to the collaboration in GitHub thing - I have my own GitHub repositories that I've been working with but never pushed a change to anyone else's.  I was going to push my branch and go from there, if possible.  Any ideas on how to do that and the problems I'm having with PyTest?

Pete

**Comment by PetePupalaikis** [comment]
I managed to get pytest running, I think properly, but only on my Linux machine and fixed a bug after running the tests.  My tests fail four tests, pass 56 and have two warnings, but these are the exact same results on my machine for the master branch I forked from.  In other words, I get the exact same test failures on my machine with our without my changes.

**Comment by nschloe** [comment]
Fixed by #274.
