### ISSUE TITLE
Boxplot with shifted axes creates additional spine path lines

### ISSUE THREAD

**Issue by kurhar** [nschloe/matplotlib2tikz#277]
https://github.com/nschloe/matplotlib2tikz/blob/1625a8939b8c3a8e308c509a1471e1360d18a82c/matplotlib2tikz/save.py#L366

Behaviour was witnessed on boxplots, but it probably happens on any type of plot. The `savefig` command adds some lines to the plot, which can be seen as `\path[...` in the file `test.tex`. One can compare `test.tex` and `test_works.tex`.

I did not want to write a pull request as the fix is tiny, the debugging has shown that the `\path[..` appeared because of the categorization of `mpl.spines.Spine` as `mpl.patches.Patch`. The solution is to change the marked line to: 
```Python
elif isinstance(child, mpl.patches.Patch) and not isinstance(child, mpl.spines.Spine):
```

MWE (admittedly not really minimal):

```python
from matplotlib2tikz import save as tikz_save
import numpy as np
import matplotlib.pyplot as plt
plt.boxplot(np.random.random([100,2]))
plt.ylim(-0.2,1.3)
plt.ylabel(np.linspace(-0.19,0.9,5))
plt.grid(True,which="major",axis="both")
tikz_save("test_works.tex",**dict(externalize_tables=False, figureheight='\\figureheight',figurewidth='\\figurewidth', encoding="utf8", strict=False,))
plt.savefig("test.pdf",bbox_inches="tight")
tikz_save("test.tex",**dict(externalize_tables=False, figureheight='\\figureheight',figurewidth='\\figurewidth', encoding="utf8", strict=False,))
```

**Comment by nschloe** [comment]
Thanks for this hint. This actually fixed two pretty old bugs (#78, #196)!
