### ISSUE TITLE
Feature request: map custom linestyle pattern

### ISSUE THREAD

**Issue by Aikhjarto** [nschloe/matplotlib2tikz#296]
It would be nice if matplotlib2tikz could support custom line styles (linestyle is given as on-off-tuples, see [linestyle description of matplotlib](https://matplotlib.org/3.0.3/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle).

There is already code in matplotlib2tikz looking to support linestyle tuples from matplotlib, starting from here:
https://github.com/nschloe/matplotlib2tikz/blob/0ea793030d1ca9f397404effa163b7631eb0e9d8/matplotlib2tikz/path.py#L296

However, custom linestyles seemed to be mapped to "dashed"

```python
import matplotlib.pyplot as plt
import matplotlib2tikz

plt.plot([1,2,3], linestyle=(1,(5,1)))
print(matplotlib2tikz.get_tikz_code('tikz'))
```

```latex
% This file was created by matplotlib2tikz v0.7.3.
\begin{tikzpicture}

\definecolor{color0}{rgb}{0.12156862745098,0.466666666666667,0.705882352941177}

\begin{axis}[
tick align=outside,
tick pos=left,
x grid style={white!69.01960784313725!black},
xmin=-0.1, xmax=2.1,
xtick style={color=black},
y grid style={white!69.01960784313725!black},
ymin=0.9, ymax=3.1,
ytick style={color=black}
]
\addplot [semithick, color0, dashed]
table {%
0 1
1 2
2 3
};
\end{axis}

\end{tikzpicture}
```

**Comment by Aikhjarto** [comment]
Found the reason: https://github.com/nschloe/matplotlib2tikz/blob/0ea793030d1ca9f397404effa163b7631eb0e9d8/matplotlib2tikz/path.py#L308
Above line checks for tuples, but matplotlib's `Line2D.get_linestyle()` does never return a tuple, see [Line2D](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/lines.py). 
There is a `Line2D.set_dashed(...)`, but no `get_dashed()`.
Dashing information is stored in `self._dashSeq`, `self._us_dashSeq`,   `self._dashOffset`, `self._us_dashOffset`, where "us" means unscaled and `self` is a matplotlib `Line2D`.

Any better idea than to use Line2D's private attributes to try the get the dash pattern?

**Comment by nschloe** [comment]
>  does never return a tuple,

Alright, yes, perhaps it did in the past. Too bad we don't have a test for this yet, but it should be easy to add, perhaps in `test_basic_sin`. Can you prepare a PR?

**Comment by Aikhjarto** [comment]
PR #297 is ready for review
