### ISSUE TITLE
Colour selected from array causes matplotlib to fail

### ISSUE THREAD

**Issue by Simclass** [nschloe/matplotlib2tikz#34]
Accessing colours stored in array causes matplotlib to fail:

```
import numpy as np
from matplotlib import cm
import matplotlib.pyplot as plt
from matplotlib2tikz import save as tikz_save

    
A = cm.jet(np.linspace(0,1,10))
plt.plot([1,2,3],[1,2,3], color = A[9])
    
tikz_save('test.tikz')
```

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

If I force the colour I've taken from the array into a list (i.e. A[9].tolist()) then everything works.

**Comment by nschloe** [comment]
This is working now. :)
