### ISSUE TITLE
missing \end{groupplot}

### ISSUE THREAD

**Issue by inkb** [nschloe/matplotlib2tikz#42]
\end{groupplot} missing from tikz output. Possible cause colorbar made using the ideas in # http://stackoverflow.com/questions/8342549/matplotlib-add-colorbar-to-a-sequence-of-line-plots. Not investigating, dissertation will take long enough to write. Please contact for more info

**Comment by nschloe** [comment]
A related bug as been fixed recently, so I assume this one is gone as well. Feel free to reopen if not.
