### ISSUE TITLE
_mpl_marker2pgfp_marker error when colors are RGB

### ISSUE THREAD

**Issue by pwohlhart** [nschloe/matplotlib2tikz#45]
line 852:
```python
if is_marker_face_color and pgfplots_marker == 'o':`
```
fails when line colors are specified in RGB triplets.

should be `any(is_marker_face_color)` or `(is_marker_face_color not is None)`?

**Comment by nschloe** [comment]
This should be fixed now. Please reopen if you still observe the bad behavior.
