### ISSUE TITLE
Data not imported to tikz file

### ISSUE THREAD

**Issue by JohnPPP** [nschloe/matplotlib2tikz#47]
Data is not imported to tikz file when this code is implemented:

(code from: http://matplotlib.org/examples/pylab_examples/subplots_demo.html)
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib2tikz import save as tikz_save

x = np.linspace(0, 2 * np.pi, 400)
y = np.sin(x ** 2)
f, axarr = plt.subplots(2, sharex=True)
tikz_save( 'sharex.tikz' );
axarr[0].plot(x, y)
axarr[0].set_title('Sharing X axis')
axarr[1].scatter(x, y)
plt.show()
```
Thank you

**Comment by nschloe** [comment]
This fix for this just went in, cf. https://github.com/nschloe/matplotlib2tikz/commit/df6e2cf6d5456073e4dfeeaf84519b45a0566f55. Will be part of the next release.
