### ISSUE TITLE
tex special characters in axis label not properly escaped

### ISSUE THREAD

**Issue by wellsbk1** [nschloe/matplotlib2tikz#50]
When including a tex special character in a plot label, such as in "Reflectance(%)", the % is included verbatim into the generated .tikz file which causes tex to interpret the text after the "%" as a comment.
mathplotlib2TikZ should trap special characters and convert % to \%

**Comment by nildt** [comment]
Encountered the same problem. I had to Escape the "%" manually.

**Comment by nschloe** [comment]
There are some ways in which you can make the matplotlib2tikz output fail to compile. The easiest is of course to insert illegal LaTeX text into the labels, e.g.,
```latex
Isn't this { a nice bracket?
```
or
```latex
Sweet_underscore.
```
In the same category falls 
```latex
Label with %-sign
```
I believe we shouldn't try to fix all LaTeX errors. Eventually, only the user can do that.

Closing, but feel free to reopen of course.

**Comment by andreassch** [comment]
The [pylatexenc](https://github.com/phfaist/pylatexenc) library can be used to LaTeX-escape special characters. What about an option to apply `pylatexenc.latexencode`'s `unicode_to_latex()` function to all label strings?
