### ISSUE TITLE
Provide a more recent matplotlib2tikz release

### ISSUE THREAD

**Issue by marbre** [nschloe/matplotlib2tikz#52]
I recently created an [ebuild](https://github.com/gentoo-science/sci/tree/master/dev-python/matplotlib2tikz) for the Gentoo science overlay to provide an easier way to install matplotlib2tikz. Currently, version 0.1.0 does not has python3 support, whereas 9999 (the default HEAD of the repo) has. Therefore, it is desirable to provide a new release. This would allow usto install a matplotlib2tikz release version, without needing to install the live ebuild, which are hard masked by default.

**Comment by nschloe** [comment]
I should definitely take more time to get m2t in shape. I'll check it out in one of the following days and be sure to release.

**Comment by nschloe** [comment]
Just released 0.2.0.

**Comment by marbre** [comment]
Thanks a lot. Bumped in the Gentoo science overlay (https://github.com/gentoo-science/sci/commit/08206b66c7079f1598c1eb67adbf1c23009b22e1).

**Comment by nschloe** [comment]
Ah cool, I didn't know Gentoo science is on GitHub now.

If there's anything else you need or notice, just let me know.
