### ISSUE TITLE
Putting % symbol in axis result in error in the final plotting in LaTeX

### ISSUE THREAD

**Issue by giacomomarchioro** [nschloe/matplotlib2tikz#81]
It happened me that I had put % in a legend title ( Like "Percentage of scattering (%)")  of course TeX read it as a comment so all the LaTeX code did not work. I took me a while to understand where was the error, I think an easy fix may avoid this experience to other users.

**Comment by nschloe** [comment]
Difficult call. There are many ways in which one can fool around with literal text in matplotlib2tikz. You used the `%` comment sign, another one would be to put `a_b` or some other illegal LaTeX character sequence. A single dollar sign `$` also makes the code uncompilable, or opening and not closing an environment like `\[` without `\]`.

I could of course go ahead and try to fix all of those things, but that would essentially mean to write a LaTeX compiler in Python.
Another sane thing thing to do is to promise that mpl2tikz doesn't fool around with the text, and the user is completely in control (and responsible) for the outcome. That's clear and easy, and typically people are happy with it. You too?

**Comment by giacomomarchioro** [comment]
Is not a big issue, in fact. I think I will see how many times it happens to me in case I will correct  it on my own. Thanks a lot for this wonderful tool!
