### ISSUE TITLE
linewidth does not change

### ISSUE THREAD

**Issue by pomodorochris** [nschloe/matplotlib2tikz#82]
I set my `lines.linewidth` and `axes.linewidth` of my plot in matplotlibrc and if I save as PDF it works. 
However, if I export the figure with `matplotlib2tikz.save`, the in the resulting .tex file the line width is always `thick`.
What am I doing wrong? I am using Matplotlib 1.5 and the example in the readme works.

**Comment by nschloe** [comment]
Do you have a _small_ example code that I can use to reproduce the problem?

**Comment by pomodorochris** [comment]
I'm sorry, it's all working fine. 
I was just confused that the linewidth was set to `thick` instead of an explicit number and it looked a lot thinner in LaTeX compared to the PDF so I didn't see the difference between thickness 1 and 2.
