### ISSUE TITLE
Legend colors incorrect with plot.errorbars()

### ISSUE THREAD

**Issue by maristal** [nschloe/matplotlib2tikz#86]
This is caused by the generated TikZ file generating 3 plots for each line with errorbars and the legend then automatically assigns both legend entries the color of the first line.

Solution could be to add forgetplot after the first plot for each line with errorbars, this way only one color per line with errorbars is assigned in the legend.

Alternatively, one could just do addlegendentry with the specified color just after the first addplot.

**Comment by nschloe** [comment]
I definitely need an MWE here to reproduce.

**Comment by nschloe** [comment]
For reference, https://github.com/matplotlib/matplotlib/issues/5222#issuecomment-147249166 may be interesting.

**Comment by nschloe** [comment]
Might be resolved in the meantime.

Feel free to reopen with an MWE if the problem persists.
