### ISSUE TITLE
Legend title support

### ISSUE THREAD

**Issue by pylipp** [nschloe/matplotlib2tikz#87]
So far, mpl2tikz does not support legend titles. Consider this mwe, 

``` python
import numpy as np 
import matplotlib.pyplot as plt 

plt.plot([1,2], label="foo")
plt.plot([1,3], label="bar")

plt.legend(loc="lower right", title="title")

from matplotlib2tikz import save as tikz_save
tikz_save("legend_title_mwe.tex")
```

the title is not displayed.
Adding a title to a legend in pgfplots has been discussed [here](http://tex.stackexchange.com/questions/2311/add-a-legend-title-to-the-legend-box-with-pgfplots). 
Have you encountered this before/found an idea for a workaround?
Thanks, pylipp

EDIT:
A possible way could be to add 

``` python
title_text = obj.get_title().get_text()
if title_text != "None":
    texts.append('%s' % title_text)
```

in [draw_legend()](https://github.com/nschloe/matplotlib2tikz/blob/f605bfae12272a2e70b885dd2267f98773a9ae63/matplotlib2tikz/legend.py) before querying any other of the object's texts.
Eventually, `\addlegendimage{empty legend}` has to be added before the first `\addplot`.

**Comment by nschloe** [comment]
This is really fiddly. One problem here is that the legend object may be parsed _after_ all `addplot`s, and the title would show up _last_. I would like to defer this until legend titles are supported in Pgfplots itself. If you open an issue for Pgfplots, feel free to reopen this bug and link it here.
